### PR TITLE
Fix issues for go-test

### PR DESCRIPTION
**Pull request by hajimehoshi**
This change enables `go test ./...` with Go modules.

* Update github.com/sirupsen/logrus version and change the package
  name.
* Replace `log.Info` with `log.Infof`
* Add `ignore` build tags to Go files in tools

### CODE REVIEW

**Comment by hajimehoshi** [comment]
ping

**Comment by mrichman** [comment]
Thanks for the PR. Will try to get to this in the next few days.

**Comment by mrichman** [comment]
@hajimehoshi I just merged in your PR. Thanks again!

I don't spend a lot of time on this tool, so this may have been broken for a while, but I did just run a quick test using the two .har files in the repo, and I'm getting errors:

```sh
./hargo f ./test/golang.org.har
...
ERRO[0000] Get https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js: net/http: invalid header field name ":authority"
```

and

```sh
./hargo f ./test/en.wikipedia.org.har
...
ERRO[0000] Get https://en.wikipedia.org/wiki/.har: net/http: invalid header field name ":scheme"
```

Looks like it might not like the colons. [This function](https://godoc.org/golang.org/x/net/http/httpguts#ValidHeaderFieldName) is the underlying validator.

Could you verify using one of your own .har files?

Thanks,
Mark

**Comment by mrichman** [comment]
It looks like only the `fetch` command is affected, btw.

**Comment by mrichman** [comment]
Disregard, I just checked in a [fix](https://github.com/mrichman/hargo/blob/master/fetch.go#L40)

**Pull request merged**
